/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as DashboardPatientsRouteImport } from './routes/_dashboard/patients'
import { Route as DashboardNotificationsRouteImport } from './routes/_dashboard/notifications'
import { Route as DashboardEarningsRouteImport } from './routes/_dashboard/earnings'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardBillingRouteImport } from './routes/_dashboard/billing'
import { Route as DashboardAppointmentsRouteImport } from './routes/_dashboard/appointments'
import { Route as DashboardMedicalRecordsIndexRouteImport } from './routes/_dashboard/medical-records/index'
import { Route as DashboardConsultationsIndexRouteImport } from './routes/_dashboard/consultations/index'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/_dashboard/settings/security'
import { Route as DashboardSettingsScheduleRouteImport } from './routes/_dashboard/settings/schedule'
import { Route as DashboardSettingsProfessionalRouteImport } from './routes/_dashboard/settings/professional'
import { Route as DashboardSettingsBillingRouteImport } from './routes/_dashboard/settings/billing'
import { Route as DashboardSettingsAccountRouteImport } from './routes/_dashboard/settings/account'
import { Route as DashboardMedicalRecordsIdRouteImport } from './routes/_dashboard/medical-records/$id'
import { Route as DashboardConsultationsIdRouteImport } from './routes/_dashboard/consultations/$id'
import { Route as DashboardAppointmentsUpcomingRouteImport } from './routes/_dashboard/appointments/upcoming'
import { Route as DashboardAppointmentsRequestsRouteImport } from './routes/_dashboard/appointments/requests'
import { Route as DashboardAppointmentsPastRouteImport } from './routes/_dashboard/appointments/past'
import { Route as DashboardAppointmentsIdVideoRouteImport } from './routes/_dashboard/appointments/$id.video'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicalRecordsIndexRoute =
  DashboardMedicalRecordsIndexRouteImport.update({
    id: '/medical-records/',
    path: '/medical-records/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardConsultationsIndexRoute =
  DashboardConsultationsIndexRouteImport.update({
    id: '/consultations/',
    path: '/consultations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsScheduleRoute =
  DashboardSettingsScheduleRouteImport.update({
    id: '/settings/schedule',
    path: '/settings/schedule',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsProfessionalRoute =
  DashboardSettingsProfessionalRouteImport.update({
    id: '/settings/professional',
    path: '/settings/professional',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMedicalRecordsIdRoute =
  DashboardMedicalRecordsIdRouteImport.update({
    id: '/medical-records/$id',
    path: '/medical-records/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardConsultationsIdRoute =
  DashboardConsultationsIdRouteImport.update({
    id: '/consultations/$id',
    path: '/consultations/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsUpcomingRoute =
  DashboardAppointmentsUpcomingRouteImport.update({
    id: '/upcoming',
    path: '/upcoming',
    getParentRoute: () => DashboardAppointmentsRoute,
  } as any)
const DashboardAppointmentsRequestsRoute =
  DashboardAppointmentsRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => DashboardAppointmentsRoute,
  } as any)
const DashboardAppointmentsPastRoute =
  DashboardAppointmentsPastRouteImport.update({
    id: '/past',
    path: '/past',
    getParentRoute: () => DashboardAppointmentsRoute,
  } as any)
const DashboardAppointmentsIdVideoRoute =
  DashboardAppointmentsIdVideoRouteImport.update({
    id: '/$id/video',
    path: '/$id/video',
    getParentRoute: () => DashboardAppointmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/appointments': typeof DashboardAppointmentsRouteWithChildren
  '/billing': typeof DashboardBillingRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/earnings': typeof DashboardEarningsRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/patients': typeof DashboardPatientsRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/appointments/past': typeof DashboardAppointmentsPastRoute
  '/appointments/requests': typeof DashboardAppointmentsRequestsRoute
  '/appointments/upcoming': typeof DashboardAppointmentsUpcomingRoute
  '/consultations/$id': typeof DashboardConsultationsIdRoute
  '/medical-records/$id': typeof DashboardMedicalRecordsIdRoute
  '/settings/account': typeof DashboardSettingsAccountRoute
  '/settings/billing': typeof DashboardSettingsBillingRoute
  '/settings/professional': typeof DashboardSettingsProfessionalRoute
  '/settings/schedule': typeof DashboardSettingsScheduleRoute
  '/settings/security': typeof DashboardSettingsSecurityRoute
  '/consultations': typeof DashboardConsultationsIndexRoute
  '/medical-records': typeof DashboardMedicalRecordsIndexRoute
  '/appointments/$id/video': typeof DashboardAppointmentsIdVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/appointments': typeof DashboardAppointmentsRouteWithChildren
  '/billing': typeof DashboardBillingRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/earnings': typeof DashboardEarningsRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/patients': typeof DashboardPatientsRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/appointments/past': typeof DashboardAppointmentsPastRoute
  '/appointments/requests': typeof DashboardAppointmentsRequestsRoute
  '/appointments/upcoming': typeof DashboardAppointmentsUpcomingRoute
  '/consultations/$id': typeof DashboardConsultationsIdRoute
  '/medical-records/$id': typeof DashboardMedicalRecordsIdRoute
  '/settings/account': typeof DashboardSettingsAccountRoute
  '/settings/billing': typeof DashboardSettingsBillingRoute
  '/settings/professional': typeof DashboardSettingsProfessionalRoute
  '/settings/schedule': typeof DashboardSettingsScheduleRoute
  '/settings/security': typeof DashboardSettingsSecurityRoute
  '/consultations': typeof DashboardConsultationsIndexRoute
  '/medical-records': typeof DashboardMedicalRecordsIndexRoute
  '/appointments/$id/video': typeof DashboardAppointmentsIdVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_dashboard/appointments': typeof DashboardAppointmentsRouteWithChildren
  '/_dashboard/billing': typeof DashboardBillingRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/earnings': typeof DashboardEarningsRoute
  '/_dashboard/notifications': typeof DashboardNotificationsRoute
  '/_dashboard/patients': typeof DashboardPatientsRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/_dashboard/appointments/past': typeof DashboardAppointmentsPastRoute
  '/_dashboard/appointments/requests': typeof DashboardAppointmentsRequestsRoute
  '/_dashboard/appointments/upcoming': typeof DashboardAppointmentsUpcomingRoute
  '/_dashboard/consultations/$id': typeof DashboardConsultationsIdRoute
  '/_dashboard/medical-records/$id': typeof DashboardMedicalRecordsIdRoute
  '/_dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/_dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/_dashboard/settings/professional': typeof DashboardSettingsProfessionalRoute
  '/_dashboard/settings/schedule': typeof DashboardSettingsScheduleRoute
  '/_dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/_dashboard/consultations/': typeof DashboardConsultationsIndexRoute
  '/_dashboard/medical-records/': typeof DashboardMedicalRecordsIndexRoute
  '/_dashboard/appointments/$id/video': typeof DashboardAppointmentsIdVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/verify-email'
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/earnings'
    | '/notifications'
    | '/patients'
    | '/auth/$authView'
    | '/appointments/past'
    | '/appointments/requests'
    | '/appointments/upcoming'
    | '/consultations/$id'
    | '/medical-records/$id'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/professional'
    | '/settings/schedule'
    | '/settings/security'
    | '/consultations'
    | '/medical-records'
    | '/appointments/$id/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/verify-email'
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/earnings'
    | '/notifications'
    | '/patients'
    | '/auth/$authView'
    | '/appointments/past'
    | '/appointments/requests'
    | '/appointments/upcoming'
    | '/consultations/$id'
    | '/medical-records/$id'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/professional'
    | '/settings/schedule'
    | '/settings/security'
    | '/consultations'
    | '/medical-records'
    | '/appointments/$id/video'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/onboarding'
    | '/verify-email'
    | '/_dashboard/appointments'
    | '/_dashboard/billing'
    | '/_dashboard/dashboard'
    | '/_dashboard/earnings'
    | '/_dashboard/notifications'
    | '/_dashboard/patients'
    | '/auth/$authView'
    | '/_dashboard/appointments/past'
    | '/_dashboard/appointments/requests'
    | '/_dashboard/appointments/upcoming'
    | '/_dashboard/consultations/$id'
    | '/_dashboard/medical-records/$id'
    | '/_dashboard/settings/account'
    | '/_dashboard/settings/billing'
    | '/_dashboard/settings/professional'
    | '/_dashboard/settings/schedule'
    | '/_dashboard/settings/security'
    | '/_dashboard/consultations/'
    | '/_dashboard/medical-records/'
    | '/_dashboard/appointments/$id/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/patients': {
      id: '/_dashboard/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/notifications': {
      id: '/_dashboard/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/earnings': {
      id: '/_dashboard/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/billing': {
      id: '/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/appointments': {
      id: '/_dashboard/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/medical-records/': {
      id: '/_dashboard/medical-records/'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof DashboardMedicalRecordsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/consultations/': {
      id: '/_dashboard/consultations/'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof DashboardConsultationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/security': {
      id: '/_dashboard/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/schedule': {
      id: '/_dashboard/settings/schedule'
      path: '/settings/schedule'
      fullPath: '/settings/schedule'
      preLoaderRoute: typeof DashboardSettingsScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/professional': {
      id: '/_dashboard/settings/professional'
      path: '/settings/professional'
      fullPath: '/settings/professional'
      preLoaderRoute: typeof DashboardSettingsProfessionalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/billing': {
      id: '/_dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/account': {
      id: '/_dashboard/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/medical-records/$id': {
      id: '/_dashboard/medical-records/$id'
      path: '/medical-records/$id'
      fullPath: '/medical-records/$id'
      preLoaderRoute: typeof DashboardMedicalRecordsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/consultations/$id': {
      id: '/_dashboard/consultations/$id'
      path: '/consultations/$id'
      fullPath: '/consultations/$id'
      preLoaderRoute: typeof DashboardConsultationsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/appointments/upcoming': {
      id: '/_dashboard/appointments/upcoming'
      path: '/upcoming'
      fullPath: '/appointments/upcoming'
      preLoaderRoute: typeof DashboardAppointmentsUpcomingRouteImport
      parentRoute: typeof DashboardAppointmentsRoute
    }
    '/_dashboard/appointments/requests': {
      id: '/_dashboard/appointments/requests'
      path: '/requests'
      fullPath: '/appointments/requests'
      preLoaderRoute: typeof DashboardAppointmentsRequestsRouteImport
      parentRoute: typeof DashboardAppointmentsRoute
    }
    '/_dashboard/appointments/past': {
      id: '/_dashboard/appointments/past'
      path: '/past'
      fullPath: '/appointments/past'
      preLoaderRoute: typeof DashboardAppointmentsPastRouteImport
      parentRoute: typeof DashboardAppointmentsRoute
    }
    '/_dashboard/appointments/$id/video': {
      id: '/_dashboard/appointments/$id/video'
      path: '/$id/video'
      fullPath: '/appointments/$id/video'
      preLoaderRoute: typeof DashboardAppointmentsIdVideoRouteImport
      parentRoute: typeof DashboardAppointmentsRoute
    }
  }
}

interface DashboardAppointmentsRouteChildren {
  DashboardAppointmentsPastRoute: typeof DashboardAppointmentsPastRoute
  DashboardAppointmentsRequestsRoute: typeof DashboardAppointmentsRequestsRoute
  DashboardAppointmentsUpcomingRoute: typeof DashboardAppointmentsUpcomingRoute
  DashboardAppointmentsIdVideoRoute: typeof DashboardAppointmentsIdVideoRoute
}

const DashboardAppointmentsRouteChildren: DashboardAppointmentsRouteChildren = {
  DashboardAppointmentsPastRoute: DashboardAppointmentsPastRoute,
  DashboardAppointmentsRequestsRoute: DashboardAppointmentsRequestsRoute,
  DashboardAppointmentsUpcomingRoute: DashboardAppointmentsUpcomingRoute,
  DashboardAppointmentsIdVideoRoute: DashboardAppointmentsIdVideoRoute,
}

const DashboardAppointmentsRouteWithChildren =
  DashboardAppointmentsRoute._addFileChildren(
    DashboardAppointmentsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRouteWithChildren
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardConsultationsIdRoute: typeof DashboardConsultationsIdRoute
  DashboardMedicalRecordsIdRoute: typeof DashboardMedicalRecordsIdRoute
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsProfessionalRoute: typeof DashboardSettingsProfessionalRoute
  DashboardSettingsScheduleRoute: typeof DashboardSettingsScheduleRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardConsultationsIndexRoute: typeof DashboardConsultationsIndexRoute
  DashboardMedicalRecordsIndexRoute: typeof DashboardMedicalRecordsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRouteWithChildren,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardConsultationsIdRoute: DashboardConsultationsIdRoute,
  DashboardMedicalRecordsIdRoute: DashboardMedicalRecordsIdRoute,
  DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsProfessionalRoute: DashboardSettingsProfessionalRoute,
  DashboardSettingsScheduleRoute: DashboardSettingsScheduleRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardConsultationsIndexRoute: DashboardConsultationsIndexRoute,
  DashboardMedicalRecordsIndexRoute: DashboardMedicalRecordsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
